// Simple icon components to replace lucide-react for minimal setup
export const Home = ({ className }) => <span className={className}>🏠</span>
export const BarChart3 = ({ className }) => <span className={className}>📊</span>
export const Palette = ({ className }) => <span className={className}>🎨</span>
export const TrendingUp = ({ className }) => <span className={className}>📈</span>
export const LogOut = ({ className }) => <span className={className}>⏹️</span>
export const User = ({ className }) => <span className={className}>👤</span>
export const Database = ({ className }) => <span className={className}>🗄️</span>
export const Upload = ({ className }) => <span className={className}>⬆️</span>
export const FileText = ({ className }) => <span className={className}>📄</span>
export const CheckCircle = ({ className }) => <span className={className}>✅</span>
export const Clock = ({ className }) => <span className={className}>🕐</span>
export const AlertCircle = ({ className }) => <span className={className}>⚠️</span>
export const Activity = ({ className }) => <span className={className}>⚡</span>
export const Users = ({ className }) => <span className={className}>👥</span>
export const DollarSign = ({ className }) => <span className={className}>💰</span>
export const Target = ({ className }) => <span className={className}>🎯</span>
export const Mail = ({ className }) => <span className={className}>📧</span>
export const Lock = ({ className }) => <span className={className}>🔒</span>
export const Figma = ({ className }) => <span className={className}>🎨</span>
export const Layout = ({ className }) => <span className={className}>📐</span>
export const Smartphone = ({ className }) => <span className={className}>📱</span>
export const Monitor = ({ className }) => <span className={className}>🖥️</span>
export const Download = ({ className }) => <span className={className}>⬇️</span>
export const Play = ({ className }) => <span className={className}>▶️</span>
export const Plus = ({ className }) => <span className={className}>➕</span>
export const Eye = ({ className }) => <span className={className}>👁️</span>
export const Calculator = ({ className }) => <span className={className}>🧮</span>
export const PlayCircle = ({ className }) => <span className={className}>⏯️</span>
export const Settings = ({ className }) => <span className={className}>⚙️</span>