name: Security Audit

on:
  schedule:
    - cron: '0 2 * * 1' # Weekly on Mondays at 2 AM
  workflow_dispatch:

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run security audit
      run: |
        # Check for common security issues
        echo "Checking for sensitive data exposure..."
        grep -r "password\|secret\|key\|token" --include="*.html" --include="*.js" --include="*.css" . || true
        
        echo "Checking file permissions..."
        find . -type f -perm /o+w || true
        
        echo "Checking for outdated dependencies..."
        npm audit || true
    
    - name: OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'https://dsd228.github.io/Dataconecta/'
        rules_file_name: '.zap/rules.tsv'
        cmd_options: '-a'